---
# tasks file for el-datadisk
- name: configure | create lvm partion on disk
  community.general.parted:
   device: "{{ item }}"
   number: 1
   flags: [ lvm ]
   state: present
  loop: "{{ device }}"

- name: Prep | add partition to list
  set_fact:
    disk_list: "{{ device | map('regex_replace', '$', '1') | list }}"

- name: debug
  debug:
    msg: "{{ disk_list }}"

- name: Prep | set fact from list of disks
  set_fact:
     disks: " {{ device | join(',') }} "

- name: debug
  debug:
    msg: "{{ disks }}"

- name: configure | create volume group vg.{{ storagename }}
  lvg:
   vg: "vg.{{ storagename }}"
   pvs: "{{ disks }}"
   pvresize: yes

- name: configure | create logical volume lg.{{ storagename }} on vg.{{ storagename }}
  lvol:
   vg: "vg.{{ storagename }}"
   lv: "lv.{{ storagename }}"
   size: 100%FREE

- name: configure | create filesystem xfs on logical volume lv.{{ storagename }}
  filesystem:
   fstype: xfs
   dev: "/dev/mapper/vg.{{ storagename }}-lv.{{ storagename }}"

- name: configure | create directory for lv.{{ storagename }} on {{ storagepath }}
  file:
   path: "{{ storagepath }}"
   state: directory

- name: configure | add fstab entry for {{ storagepath }}
  mount:
   name: "{{ storagepath }}"
   src: "/dev/mapper/vg.{{ storagename }}-lv.{{ storagename }}"
   fstype: xfs
   opts: defaults
   state: present

- name: post | mount disk
  shell: mount -a
  args:
   warn: false